controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

lexik_jwt_login:
  path: /api/login
  controller: lexik_jwt_authentication.controller.authentication
  methods: [POST]