security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/users$, roles: PUBLIC_ACCESS, methods: [POST] }

        - { path: ^/api/users, roles: ROLE_ADMIN }

        - { path: ^/api/assistants, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/assistant_tools, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/knowledge_bases, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/tools, roles: IS_AUTHENTICATED_FULLY }

        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

