vich_uploader:
    db_driver: orm
    mappings:
        knowledge_file:
            uri_prefix: /uploads/knowledge
            upload_destination: '%kernel.project_dir%/public/uploads/knowledgebases'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
